import { MigrationInterface, QueryRunner } from "typeorm";

export class AddServiceEntity1754594121186 implements MigrationInterface {
    name = 'AddServiceEntity1754594121186'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`service\` (\`id\` varchar(36) NOT NULL, \`full_name\` varchar(255) NOT NULL, \`fonction\` varchar(255) NULL, \`description\` text NULL, \`price\` decimal(10,2) NULL, \`imageUrls\` json NULL, \`companyId\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`categoryId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`permissions\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`otp_entity\` DROP FOREIGN KEY \`FK_d8d7d1cd42eafbb1d6c61b2ff37\``);
        await queryRunner.query(`ALTER TABLE \`otp_entity\` CHANGE \`expiresAt\` \`expiresAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`otp_entity\` CHANGE \`userId\` \`userId\` varchar(36) NULL`);
        await queryRunner.query(`DROP INDEX \`IDX_6afadda7821d38fe7058240504\` ON \`reserv_service\``);
        await queryRunner.query(`ALTER TABLE \`reserv_service\` CHANGE \`date\` \`date\` timestamp NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reserv_service\` CHANGE \`userId\` \`userId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`reserv_service\` CHANGE \`providerId\` \`providerId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`category\` DROP FOREIGN KEY \`FK_1117b4fcb3cd4abb4383e1c2743\``);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`image\` \`image\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`type\` \`type\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`color\` \`color\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`parent_id\` \`parent_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`image_product_entity\` DROP FOREIGN KEY \`FK_bcec19dad6b0a68e42913470653\``);
        await queryRunner.query(`ALTER TABLE \`image_product_entity\` CHANGE \`productId\` \`productId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`rental_contracts\` CHANGE \`startDate\` \`startDate\` timestamp NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`rental_contracts\` CHANGE \`endDate\` \`endDate\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_9a5f6868c96e0069e699f33e124\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_f3cd3ac28f81bbb08bd7d119e04\``);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`price\` \`price\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`detail_price_original\` \`detail_price_original\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`gros_price_original\` \`gros_price_original\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`detail\` \`detail\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`gros\` \`gros\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`registrationNumber\` \`registrationNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`brand\` \`brand\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`model\` \`model\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`year\` \`year\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`dailyRate\` \`dailyRate\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`salePrice\` \`salePrice\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`color\` \`color\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`ingredients\` \`ingredients\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`quantity\` \`quantity\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`image\` \`image\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`category_id\` \`category_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`measureId\` \`measureId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`companyAddress\` \`companyAddress\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`vatNumber\` \`vatNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`registrationDocumentUrl\` \`registrationDocumentUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`warehouseLocation\` \`warehouseLocation\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`banner\` \`banner\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`logo\` \`logo\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`email\` \`email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`website\` \`website\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`delivery_minutes\` \`delivery_minutes\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`distance_km\` \`distance_km\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`open_time\` \`open_time\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`address\` \`address\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`latitude\` \`latitude\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`longitude\` \`longitude\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`departureLocation\` \`departureLocation\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`arrivalLocation\` \`arrivalLocation\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`departureDate\` \`departureDate\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`arrivalDate\` \`arrivalDate\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`reservationDate\` \`reservationDate\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`price\` \`price\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`vehicleModel\` \`vehicleModel\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`plateNumber\` \`plateNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`driverIncluded\` \`driverIncluded\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`seatNumber\` \`seatNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`address_user\` DROP FOREIGN KEY \`FK_2990f79ef381b67c8d5e3474981\``);
        await queryRunner.query(`ALTER TABLE \`address_user\` CHANGE \`userId\` \`userId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_orders\` DROP FOREIGN KEY \`FK_99d5f29c6ea3cfca35f10759984\``);
        await queryRunner.query(`ALTER TABLE \`sub_orders\` DROP FOREIGN KEY \`FK_8960953c62922b12d952670105b\``);
        await queryRunner.query(`ALTER TABLE \`sub_orders\` CHANGE \`invoiceNumber\` \`invoiceNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_orders\` CHANGE \`orderId\` \`orderId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_orders\` CHANGE \`companyId\` \`companyId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`invoiceNumber\` \`invoiceNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`status\` \`status\` enum ('PENDING', 'VALIDATED', 'PROCESSING', 'COMPLETED', 'DELIVERED', 'REJECTED ') NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_993cd4e93dc84f17341702d059e\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_ca511885113fd45b6de7ce6dd43\``);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`image\` \`image\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`country\` \`country\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`city\` \`city\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`address\` \`address\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`preferredLanguage\` \`preferredLanguage\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`loyaltyPoints\` \`loyaltyPoints\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`dateOfBirth\` \`dateOfBirth\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`vehicleType\` \`vehicleType\` enum ('MOTO', 'CAMION', 'VÉLO', 'VOITURE') NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`plateNumber\` \`plateNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`licenseDocumentUrl\` \`licenseDocumentUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`twoFASecret\` \`twoFASecret\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`socketId\` \`socketId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`activeCompanyId\` \`activeCompanyId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`defaultAddressId\` \`defaultAddressId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` DROP FOREIGN KEY \`FK_6c36c7c118fa460ce0dbef078a1\``);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` DROP FOREIGN KEY \`FK_ec55a6c7815580309ec3aa1f808\``);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` DROP FOREIGN KEY \`FK_695609416765da022418983a827\``);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` CHANGE \`userId\` \`userId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` CHANGE \`companyId\` \`companyId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` CHANGE \`roleId\` \`roleId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`assign_permissions\` DROP FOREIGN KEY \`FK_ef1d0964292fac8cc56878638e8\``);
        await queryRunner.query(`ALTER TABLE \`assign_permissions\` DROP FOREIGN KEY \`FK_ba4be57d802e47d3726bb784af3\``);
        await queryRunner.query(`ALTER TABLE \`assign_permissions\` CHANGE \`userHasCompanyId\` \`userHasCompanyId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`assign_permissions\` CHANGE \`permissionId\` \`permissionId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`type_companies\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`type_companies\` CHANGE \`image\` \`image\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`delivery\` DROP FOREIGN KEY \`FK_c2ec8308561631ed7fb74d96333\``);
        await queryRunner.query(`ALTER TABLE \`delivery\` DROP FOREIGN KEY \`FK_a3b8af1ce2f6e143d416d83080a\``);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`deliveryNotes\` \`deliveryNotes\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`deliveredAt\` \`deliveredAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`estimatedDeliveryTime\` \`estimatedDeliveryTime\` time NULL`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`signatureImageUrl\` \`signatureImageUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`signedAt\` \`signedAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`deliveryCompanyId\` \`deliveryCompanyId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`user_id\` \`user_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`tracking\` DROP FOREIGN KEY \`FK_860f63fd48b93107167e4cd8b41\``);
        await queryRunner.query(`ALTER TABLE \`tracking\` CHANGE \`location\` \`location\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tracking\` CHANGE \`notes\` \`notes\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tracking\` CHANGE \`delivery_id\` \`delivery_id\` varchar(36) NULL`);
        await queryRunner.query(`CREATE INDEX \`IDX_6afadda7821d38fe7058240504\` ON \`reserv_service\` (\`userId\`, \`date\`)`);
        await queryRunner.query(`ALTER TABLE \`otp_entity\` ADD CONSTRAINT \`FK_d8d7d1cd42eafbb1d6c61b2ff37\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reserv_service\` ADD CONSTRAINT \`FK_e7543e0c640ac8f8145427d4296\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reserv_service\` ADD CONSTRAINT \`FK_93488b0b86dabc369786635f664\` FOREIGN KEY (\`providerId\`) REFERENCES \`service\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`service\` ADD CONSTRAINT \`FK_cb169715cbb8c74f263ba192ca8\` FOREIGN KEY (\`categoryId\`) REFERENCES \`category\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`service\` ADD CONSTRAINT \`FK_02fbdab4c697f74792472b88546\` FOREIGN KEY (\`companyId\`) REFERENCES \`company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`category\` ADD CONSTRAINT \`FK_1117b4fcb3cd4abb4383e1c2743\` FOREIGN KEY (\`parent_id\`) REFERENCES \`category\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`image_product_entity\` ADD CONSTRAINT \`FK_bcec19dad6b0a68e42913470653\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_9a5f6868c96e0069e699f33e124\` FOREIGN KEY (\`category_id\`) REFERENCES \`category\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_f3cd3ac28f81bbb08bd7d119e04\` FOREIGN KEY (\`measureId\`) REFERENCES \`measures\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`address_user\` ADD CONSTRAINT \`FK_2990f79ef381b67c8d5e3474981\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sub_orders\` ADD CONSTRAINT \`FK_99d5f29c6ea3cfca35f10759984\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sub_orders\` ADD CONSTRAINT \`FK_8960953c62922b12d952670105b\` FOREIGN KEY (\`companyId\`) REFERENCES \`company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_993cd4e93dc84f17341702d059e\` FOREIGN KEY (\`activeCompanyId\`) REFERENCES \`company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_ca511885113fd45b6de7ce6dd43\` FOREIGN KEY (\`defaultAddressId\`) REFERENCES \`address_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` ADD CONSTRAINT \`FK_6c36c7c118fa460ce0dbef078a1\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` ADD CONSTRAINT \`FK_ec55a6c7815580309ec3aa1f808\` FOREIGN KEY (\`companyId\`) REFERENCES \`company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` ADD CONSTRAINT \`FK_695609416765da022418983a827\` FOREIGN KEY (\`roleId\`) REFERENCES \`role_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`assign_permissions\` ADD CONSTRAINT \`FK_ef1d0964292fac8cc56878638e8\` FOREIGN KEY (\`userHasCompanyId\`) REFERENCES \`user_has_company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`assign_permissions\` ADD CONSTRAINT \`FK_ba4be57d802e47d3726bb784af3\` FOREIGN KEY (\`permissionId\`) REFERENCES \`permissions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`delivery\` ADD CONSTRAINT \`FK_c2ec8308561631ed7fb74d96333\` FOREIGN KEY (\`deliveryCompanyId\`) REFERENCES \`company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`delivery\` ADD CONSTRAINT \`FK_a3b8af1ce2f6e143d416d83080a\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tracking\` ADD CONSTRAINT \`FK_860f63fd48b93107167e4cd8b41\` FOREIGN KEY (\`delivery_id\`) REFERENCES \`delivery\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`tracking\` DROP FOREIGN KEY \`FK_860f63fd48b93107167e4cd8b41\``);
        await queryRunner.query(`ALTER TABLE \`delivery\` DROP FOREIGN KEY \`FK_a3b8af1ce2f6e143d416d83080a\``);
        await queryRunner.query(`ALTER TABLE \`delivery\` DROP FOREIGN KEY \`FK_c2ec8308561631ed7fb74d96333\``);
        await queryRunner.query(`ALTER TABLE \`assign_permissions\` DROP FOREIGN KEY \`FK_ba4be57d802e47d3726bb784af3\``);
        await queryRunner.query(`ALTER TABLE \`assign_permissions\` DROP FOREIGN KEY \`FK_ef1d0964292fac8cc56878638e8\``);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` DROP FOREIGN KEY \`FK_695609416765da022418983a827\``);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` DROP FOREIGN KEY \`FK_ec55a6c7815580309ec3aa1f808\``);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` DROP FOREIGN KEY \`FK_6c36c7c118fa460ce0dbef078a1\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_ca511885113fd45b6de7ce6dd43\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_993cd4e93dc84f17341702d059e\``);
        await queryRunner.query(`ALTER TABLE \`sub_orders\` DROP FOREIGN KEY \`FK_8960953c62922b12d952670105b\``);
        await queryRunner.query(`ALTER TABLE \`sub_orders\` DROP FOREIGN KEY \`FK_99d5f29c6ea3cfca35f10759984\``);
        await queryRunner.query(`ALTER TABLE \`address_user\` DROP FOREIGN KEY \`FK_2990f79ef381b67c8d5e3474981\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_f3cd3ac28f81bbb08bd7d119e04\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_9a5f6868c96e0069e699f33e124\``);
        await queryRunner.query(`ALTER TABLE \`image_product_entity\` DROP FOREIGN KEY \`FK_bcec19dad6b0a68e42913470653\``);
        await queryRunner.query(`ALTER TABLE \`category\` DROP FOREIGN KEY \`FK_1117b4fcb3cd4abb4383e1c2743\``);
        await queryRunner.query(`ALTER TABLE \`service\` DROP FOREIGN KEY \`FK_02fbdab4c697f74792472b88546\``);
        await queryRunner.query(`ALTER TABLE \`service\` DROP FOREIGN KEY \`FK_cb169715cbb8c74f263ba192ca8\``);
        await queryRunner.query(`ALTER TABLE \`reserv_service\` DROP FOREIGN KEY \`FK_93488b0b86dabc369786635f664\``);
        await queryRunner.query(`ALTER TABLE \`reserv_service\` DROP FOREIGN KEY \`FK_e7543e0c640ac8f8145427d4296\``);
        await queryRunner.query(`ALTER TABLE \`otp_entity\` DROP FOREIGN KEY \`FK_d8d7d1cd42eafbb1d6c61b2ff37\``);
        await queryRunner.query(`DROP INDEX \`IDX_6afadda7821d38fe7058240504\` ON \`reserv_service\``);
        await queryRunner.query(`ALTER TABLE \`tracking\` CHANGE \`delivery_id\` \`delivery_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tracking\` CHANGE \`notes\` \`notes\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tracking\` CHANGE \`location\` \`location\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tracking\` ADD CONSTRAINT \`FK_860f63fd48b93107167e4cd8b41\` FOREIGN KEY (\`delivery_id\`) REFERENCES \`delivery\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`user_id\` \`user_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`deliveryCompanyId\` \`deliveryCompanyId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`signedAt\` \`signedAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`signatureImageUrl\` \`signatureImageUrl\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`estimatedDeliveryTime\` \`estimatedDeliveryTime\` time NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`deliveredAt\` \`deliveredAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`deliveryNotes\` \`deliveryNotes\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`delivery\` ADD CONSTRAINT \`FK_a3b8af1ce2f6e143d416d83080a\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`delivery\` ADD CONSTRAINT \`FK_c2ec8308561631ed7fb74d96333\` FOREIGN KEY (\`deliveryCompanyId\`) REFERENCES \`company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`type_companies\` CHANGE \`image\` \`image\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`type_companies\` CHANGE \`description\` \`description\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`assign_permissions\` CHANGE \`permissionId\` \`permissionId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`assign_permissions\` CHANGE \`userHasCompanyId\` \`userHasCompanyId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`assign_permissions\` ADD CONSTRAINT \`FK_ba4be57d802e47d3726bb784af3\` FOREIGN KEY (\`permissionId\`) REFERENCES \`permissions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`assign_permissions\` ADD CONSTRAINT \`FK_ef1d0964292fac8cc56878638e8\` FOREIGN KEY (\`userHasCompanyId\`) REFERENCES \`user_has_company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` CHANGE \`roleId\` \`roleId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` CHANGE \`companyId\` \`companyId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` CHANGE \`userId\` \`userId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` ADD CONSTRAINT \`FK_695609416765da022418983a827\` FOREIGN KEY (\`roleId\`) REFERENCES \`role_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` ADD CONSTRAINT \`FK_ec55a6c7815580309ec3aa1f808\` FOREIGN KEY (\`companyId\`) REFERENCES \`company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` ADD CONSTRAINT \`FK_6c36c7c118fa460ce0dbef078a1\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`defaultAddressId\` \`defaultAddressId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`activeCompanyId\` \`activeCompanyId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`socketId\` \`socketId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`twoFASecret\` \`twoFASecret\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`licenseDocumentUrl\` \`licenseDocumentUrl\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`plateNumber\` \`plateNumber\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`vehicleType\` \`vehicleType\` enum ('MOTO', 'CAMION', 'VÉLO', 'VOITURE') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`dateOfBirth\` \`dateOfBirth\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`loyaltyPoints\` \`loyaltyPoints\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`preferredLanguage\` \`preferredLanguage\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`address\` \`address\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`city\` \`city\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`country\` \`country\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`image\` \`image\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_ca511885113fd45b6de7ce6dd43\` FOREIGN KEY (\`defaultAddressId\`) REFERENCES \`address_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_993cd4e93dc84f17341702d059e\` FOREIGN KEY (\`activeCompanyId\`) REFERENCES \`company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`status\` \`status\` enum ('PENDING', 'VALIDATED', 'PROCESSING', 'COMPLETED', 'DELIVERED', 'REJECTED') NOT NULL DEFAULT ''PENDING''`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`invoiceNumber\` \`invoiceNumber\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sub_orders\` CHANGE \`companyId\` \`companyId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sub_orders\` CHANGE \`orderId\` \`orderId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sub_orders\` CHANGE \`invoiceNumber\` \`invoiceNumber\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sub_orders\` ADD CONSTRAINT \`FK_8960953c62922b12d952670105b\` FOREIGN KEY (\`companyId\`) REFERENCES \`company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sub_orders\` ADD CONSTRAINT \`FK_99d5f29c6ea3cfca35f10759984\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`address_user\` CHANGE \`userId\` \`userId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`address_user\` ADD CONSTRAINT \`FK_2990f79ef381b67c8d5e3474981\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`seatNumber\` \`seatNumber\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`driverIncluded\` \`driverIncluded\` tinyint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`plateNumber\` \`plateNumber\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`vehicleModel\` \`vehicleModel\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`price\` \`price\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`reservationDate\` \`reservationDate\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`arrivalDate\` \`arrivalDate\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`departureDate\` \`departureDate\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`arrivalLocation\` \`arrivalLocation\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`departureLocation\` \`departureLocation\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`longitude\` \`longitude\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`latitude\` \`latitude\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`address\` \`address\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`open_time\` \`open_time\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`distance_km\` \`distance_km\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`delivery_minutes\` \`delivery_minutes\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`website\` \`website\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`email\` \`email\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`logo\` \`logo\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`banner\` \`banner\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`warehouseLocation\` \`warehouseLocation\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`registrationDocumentUrl\` \`registrationDocumentUrl\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`vatNumber\` \`vatNumber\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`companyAddress\` \`companyAddress\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`measureId\` \`measureId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`category_id\` \`category_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`image\` \`image\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`quantity\` \`quantity\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`ingredients\` \`ingredients\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`color\` \`color\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`salePrice\` \`salePrice\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`dailyRate\` \`dailyRate\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`year\` \`year\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`model\` \`model\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`brand\` \`brand\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`registrationNumber\` \`registrationNumber\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`gros\` \`gros\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`detail\` \`detail\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`gros_price_original\` \`gros_price_original\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`detail_price_original\` \`detail_price_original\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`price\` \`price\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_f3cd3ac28f81bbb08bd7d119e04\` FOREIGN KEY (\`measureId\`) REFERENCES \`measures\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_9a5f6868c96e0069e699f33e124\` FOREIGN KEY (\`category_id\`) REFERENCES \`category\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rental_contracts\` CHANGE \`endDate\` \`endDate\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rental_contracts\` CHANGE \`startDate\` \`startDate\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`image_product_entity\` CHANGE \`productId\` \`productId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`image_product_entity\` ADD CONSTRAINT \`FK_bcec19dad6b0a68e42913470653\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`parent_id\` \`parent_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`color\` \`color\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`type\` \`type\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`image\` \`image\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`category\` ADD CONSTRAINT \`FK_1117b4fcb3cd4abb4383e1c2743\` FOREIGN KEY (\`parent_id\`) REFERENCES \`category\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reserv_service\` CHANGE \`providerId\` \`providerId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reserv_service\` CHANGE \`userId\` \`userId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reserv_service\` CHANGE \`date\` \`date\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`CREATE INDEX \`IDX_6afadda7821d38fe7058240504\` ON \`reserv_service\` (\`userId\`, \`date\`)`);
        await queryRunner.query(`ALTER TABLE \`otp_entity\` CHANGE \`userId\` \`userId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`otp_entity\` CHANGE \`expiresAt\` \`expiresAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`otp_entity\` ADD CONSTRAINT \`FK_d8d7d1cd42eafbb1d6c61b2ff37\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`permissions\` CHANGE \`description\` \`description\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`DROP TABLE \`service\``);
    }

}
