import { MigrationInterface, QueryRunner } from "typeorm";

export class FixRentalContractsForeignKey1765877940519 implements MigrationInterface {
    name = 'FixRentalContractsForeignKey1765877940519'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`permissions\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`otp_entity\` DROP FOREIGN KEY \`FK_d8d7d1cd42eafbb1d6c61b2ff37\``);
        await queryRunner.query(`ALTER TABLE \`otp_entity\` CHANGE \`expiresAt\` \`expiresAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`otp_entity\` CHANGE \`userId\` \`userId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`image_product_entity\` DROP FOREIGN KEY \`FK_bcec19dad6b0a68e42913470653\``);
        await queryRunner.query(`ALTER TABLE \`image_product_entity\` CHANGE \`productId\` \`productId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`product_variations\` DROP FOREIGN KEY \`FK_a0def70d267bba28e183f92c7a8\``);
        await queryRunner.query(`ALTER TABLE \`product_variations\` CHANGE \`weight\` \`weight\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`product_variations\` CHANGE \`length\` \`length\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`product_variations\` CHANGE \`width\` \`width\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`product_variations\` CHANGE \`height\` \`height\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`product_variations\` CHANGE \`barcode\` \`barcode\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`product_variations\` CHANGE \`imageId\` \`imageId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` CHANGE \`displayName\` \`displayName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` CHANGE \`color\` \`color\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` CHANGE \`imageUrl\` \`imageUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` CHANGE \`position\` \`position\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`attributes\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`prestataires\` CHANGE \`email\` \`email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`prestataires\` CHANGE \`phone\` \`phone\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`prestataires\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`prestataires\` CHANGE \`image\` \`image\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`prestataires\` CHANGE \`experience\` \`experience\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`prestataires\` CHANGE \`competence\` \`competence\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`prestataires\` CHANGE \`specialite\` \`specialite\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`service_has_prestataire\` CHANGE \`tarif\` \`tarif\` decimal NULL`);
        await queryRunner.query(`ALTER TABLE \`services\` DROP FOREIGN KEY \`FK_25334fffe4ce341dd1da38acbd9\``);
        await queryRunner.query(`ALTER TABLE \`services\` DROP FOREIGN KEY \`FK_5b16b7b2857ee7d0efab4cf3df1\``);
        await queryRunner.query(`ALTER TABLE \`services\` DROP FOREIGN KEY \`FK_034b52310c2d211bc979c3cc4e8\``);
        await queryRunner.query(`ALTER TABLE \`services\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`services\` CHANGE \`price\` \`price\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`services\` CHANGE \`images\` \`images\` longtext NULL`);
        await queryRunner.query(`ALTER TABLE \`services\` CHANGE \`companyId\` \`companyId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`services\` CHANGE \`measureId\` \`measureId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`services\` CHANGE \`categoryId\` \`categoryId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`product_specification_value\` CHANGE \`value\` \`value\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`specification\` CHANGE \`image\` \`image\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`specification\` CHANGE \`unit\` \`unit\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`specification\` DROP COLUMN \`options\``);
        await queryRunner.query(`ALTER TABLE \`specification\` ADD \`options\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`category\` DROP FOREIGN KEY \`FK_1117b4fcb3cd4abb4383e1c2743\``);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`image\` \`image\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`type\` \`type\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`color\` \`color\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`parent_id\` \`parent_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`rental_contracts\` CHANGE \`startDate\` \`startDate\` timestamp NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`rental_contracts\` CHANGE \`endDate\` \`endDate\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`rental_contracts\` CHANGE \`rentalNumber\` \`rentalNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`sale_transaction\` CHANGE \`paymentStatus\` \`paymentStatus\` enum ('PENDING', 'PAID', 'VALIDATED', 'PROCESSING', 'COMPLETED', 'DELIVERED', 'REJECTED ') NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE \`sale_transaction\` CHANGE \`saleNumber\` \`saleNumber\` varchar(255) NULL`);
        await queryRunner.query(`DROP INDEX \`IDX_5629f2896ea05ee200f7a96af4\` ON \`wishlists\``);
        await queryRunner.query(`ALTER TABLE \`wishlists\` CHANGE \`shopType\` \`shopType\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`wishlists\` CHANGE \`userId\` \`userId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`wishlists\` CHANGE \`productId\` \`productId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`brands\` CHANGE \`image\` \`image\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`brands\` CHANGE \`type\` \`type\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`room_availability\` CHANGE \`productId\` \`productId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`specialRequest\` \`specialRequest\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`reason\` \`reason\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`invoiceNumber\` \`invoiceNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`price\` \`price\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`detail_price_original\` \`detail_price_original\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`gros_price_original\` \`gros_price_original\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`detail\` \`detail\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`gros\` \`gros\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`type\` \`type\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`registrationNumber\` \`registrationNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`model\` \`model\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`year\` \`year\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`dailyRate\` \`dailyRate\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`salePrice\` \`salePrice\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`color\` \`color\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`dailyRate_price_original\` \`dailyRate_price_original\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`ingredients\` \`ingredients\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`image\` \`image\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`localization\` \`localization\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`category_id\` \`category_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`brand_id\` \`brand_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`measureId\` \`measureId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`room_image\` CHANGE \`altText\` \`altText\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`room_image\` CHANGE \`roomId\` \`roomId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`booking\` CHANGE \`userId\` \`userId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`room\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`room\` CHANGE \`measureId\` \`measureId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`measures\` CHANGE \`company_id\` \`company_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`countries\` CHANGE \`code\` \`code\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`companyAddress\` \`companyAddress\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`vatNumber\` \`vatNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`registrationDocumentUrl\` \`registrationDocumentUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`warehouseLocation\` \`warehouseLocation\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`banner\` \`banner\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`logo\` \`logo\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`email\` \`email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`website\` \`website\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`delivery_minutes\` \`delivery_minutes\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`distance_km\` \`distance_km\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`open_time\` \`open_time\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`address\` \`address\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`latitude\` \`latitude\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`longitude\` \`longitude\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`localCurrency\` \`localCurrency\` varchar(22) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`countryId\` \`countryId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`categoryId\` \`categoryId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`cityId\` \`cityId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`departureLocation\` \`departureLocation\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`arrivalLocation\` \`arrivalLocation\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`departureDate\` \`departureDate\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`arrivalDate\` \`arrivalDate\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`reservationDate\` \`reservationDate\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`seatNumber\` \`seatNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`address_user\` CHANGE \`userId\` \`userId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_orders\` CHANGE \`invoiceNumber\` \`invoiceNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_orders\` CHANGE \`status\` \`status\` enum ('PENDING', 'VALIDATED', 'PROCESSING', 'COMPLETED', 'DELIVERED', 'REJECTED ') NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE \`sub_orders\` CHANGE \`orderId\` \`orderId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_orders\` CHANGE \`companyId\` \`companyId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`tracking\` CHANGE \`location\` \`location\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tracking\` CHANGE \`notes\` \`notes\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tracking\` CHANGE \`delivery_id\` \`delivery_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`notes\` \`notes\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`deliveredAt\` \`deliveredAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`estimatedDeliveryTime\` \`estimatedDeliveryTime\` time NULL`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`signatureImageUrl\` \`signatureImageUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`signedAt\` \`signedAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`user_id\` \`user_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`order_id\` \`order_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`invoiceNumber\` \`invoiceNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`status\` \`status\` enum ('PENDING', 'VALIDATED', 'PROCESSING', 'COMPLETED', 'DELIVERED', 'REJECTED ') NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`pin\` \`pin\` varchar(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`branches\` CHANGE \`address\` \`address\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`branches\` CHANGE \`phone\` \`phone\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`branches\` CHANGE \`email\` \`email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`branches\` CHANGE \`countryId\` \`countryId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`branches\` CHANGE \`cityId\` \`cityId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_has_resource\` CHANGE \`userId\` \`userId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_has_resource\` CHANGE \`resourceId\` \`resourceId\` varchar(36) NULL`);
        await queryRunner.query(`DROP INDEX \`IDX_17f1be9ef9af82fee0ab2f6bcc\` ON \`branch_user_platform_role_resources\``);
        await queryRunner.query(`ALTER TABLE \`branch_user_platform_role_resources\` CHANGE \`branchId\` \`branchId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`branch_user_platform_role_resources\` CHANGE \`userPlatformRoleId\` \`userPlatformRoleId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`branch_user_platform_role_resources\` CHANGE \`resourceId\` \`resourceId\` varchar(36) NULL`);
        await queryRunner.query(`DROP INDEX \`IDX_52a3990233b74dd8bc03acae89\` ON \`user_platform_roles\``);
        await queryRunner.query(`ALTER TABLE \`user_platform_roles\` CHANGE \`userId\` \`userId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_platform_roles\` CHANGE \`platformId\` \`platformId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_platform_roles\` CHANGE \`roleId\` \`roleId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`colis\` CHANGE \`driverId\` \`driverId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`colis\` CHANGE \`photos\` \`photos\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`email\` \`email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phone\` \`phone\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`image\` \`image\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`country\` \`country\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`city\` \`city\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`provider\` \`provider\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`address\` \`address\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`preferredLanguage\` \`preferredLanguage\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`loyaltyPoints\` \`loyaltyPoints\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`dateOfBirth\` \`dateOfBirth\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`vehicleType\` \`vehicleType\` enum ('MOTO', 'CAMION', 'VÉLO', 'VOITURE') NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`plateNumber\` \`plateNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`licenseDocumentUrl\` \`licenseDocumentUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`twoFASecret\` \`twoFASecret\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`socketId\` \`socketId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`activeCompanyId\` \`activeCompanyId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`defaultAddressId\` \`defaultAddressId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` CHANGE \`userId\` \`userId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` CHANGE \`companyId\` \`companyId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` CHANGE \`roleId\` \`roleId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`assign_permissions\` CHANGE \`userHasCompanyId\` \`userHasCompanyId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`assign_permissions\` CHANGE \`permissionId\` \`permissionId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`type_companies\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`type_companies\` CHANGE \`image\` \`image\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`appName\` \`appName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`slogan\` \`slogan\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`logo\` \`logo\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`email\` \`email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`phone\` \`phone\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`service_phone\` \`service_phone\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`market_phone\` \`market_phone\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`restaurant_phone\` \`restaurant_phone\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`car_phone\` \`car_phone\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`rental_phone\` \`rental_phone\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`booking_phone\` \`booking_phone\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`address\` \`address\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`support\` \`support\` longtext NULL`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`seo\` \`seo\` longtext NULL`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`config\` \`config\` longtext NULL`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`privacyPolicy\` \`privacyPolicy\` longtext NULL`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`termsOfUse\` \`termsOfUse\` longtext NULL`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`legal\` \`legal\` longtext NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_5629f2896ea05ee200f7a96af4\` ON \`wishlists\` (\`userId\`, \`productId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_17f1be9ef9af82fee0ab2f6bcc\` ON \`branch_user_platform_role_resources\` (\`branchId\`, \`userPlatformRoleId\`, \`resourceId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_52a3990233b74dd8bc03acae89\` ON \`user_platform_roles\` (\`userId\`, \`platformId\`, \`roleId\`)`);
        await queryRunner.query(`ALTER TABLE \`otp_entity\` ADD CONSTRAINT \`FK_d8d7d1cd42eafbb1d6c61b2ff37\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`image_product_entity\` ADD CONSTRAINT \`FK_bcec19dad6b0a68e42913470653\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_variations\` ADD CONSTRAINT \`FK_a0def70d267bba28e183f92c7a8\` FOREIGN KEY (\`imageId\`) REFERENCES \`image_product_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`services\` ADD CONSTRAINT \`FK_034b52310c2d211bc979c3cc4e8\` FOREIGN KEY (\`categoryId\`) REFERENCES \`category\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`services\` ADD CONSTRAINT \`FK_25334fffe4ce341dd1da38acbd9\` FOREIGN KEY (\`companyId\`) REFERENCES \`company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`services\` ADD CONSTRAINT \`FK_5b16b7b2857ee7d0efab4cf3df1\` FOREIGN KEY (\`measureId\`) REFERENCES \`measures\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`category\` ADD CONSTRAINT \`FK_1117b4fcb3cd4abb4383e1c2743\` FOREIGN KEY (\`parent_id\`) REFERENCES \`category\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rental_contracts\` ADD CONSTRAINT \`FK_b294413af7e26f6dbf73f8ee7e7\` FOREIGN KEY (\`customerId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sale_transaction\` ADD CONSTRAINT \`FK_b517ae8cf8b49878540f36fe038\` FOREIGN KEY (\`customerId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`wishlists\` ADD CONSTRAINT \`FK_4f3c30555daa6ab0b70a1db772c\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`wishlists\` ADD CONSTRAINT \`FK_063c6f46d6cbebf35f3a5ec3d4e\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`room_availability\` ADD CONSTRAINT \`FK_14d1e68b0329da0642313398db2\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reservations\` ADD CONSTRAINT \`FK_aa0e1cc2c4f54da32bf8282154c\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_9a5f6868c96e0069e699f33e124\` FOREIGN KEY (\`category_id\`) REFERENCES \`category\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_1530a6f15d3c79d1b70be98f2be\` FOREIGN KEY (\`brand_id\`) REFERENCES \`brands\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_f3cd3ac28f81bbb08bd7d119e04\` FOREIGN KEY (\`measureId\`) REFERENCES \`measures\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`room_image\` ADD CONSTRAINT \`FK_8652478a73dd49bbfcf14775e3e\` FOREIGN KEY (\`roomId\`) REFERENCES \`room\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`booking\` ADD CONSTRAINT \`FK_336b3f4a235460dc93645fbf222\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`room\` ADD CONSTRAINT \`FK_a81b8055e21ed129a8c3b153042\` FOREIGN KEY (\`measureId\`) REFERENCES \`measures\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`measures\` ADD CONSTRAINT \`FK_10e59b90eb894294b367bddd689\` FOREIGN KEY (\`company_id\`) REFERENCES \`company\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company\` ADD CONSTRAINT \`FK_9731df468316e5b1a689b906240\` FOREIGN KEY (\`countryId\`) REFERENCES \`countries\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company\` ADD CONSTRAINT \`FK_4b47f280258a2e73f5c44497e83\` FOREIGN KEY (\`categoryId\`) REFERENCES \`category\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company\` ADD CONSTRAINT \`FK_d37b1b0cc9656c160b5464ac4f3\` FOREIGN KEY (\`cityId\`) REFERENCES \`cities\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` ADD CONSTRAINT \`FK_3e16264f60cbd62bf1906b79815\` FOREIGN KEY (\`clientId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`address_user\` ADD CONSTRAINT \`FK_2990f79ef381b67c8d5e3474981\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sub_orders\` ADD CONSTRAINT \`FK_99d5f29c6ea3cfca35f10759984\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sub_orders\` ADD CONSTRAINT \`FK_8960953c62922b12d952670105b\` FOREIGN KEY (\`companyId\`) REFERENCES \`company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tracking\` ADD CONSTRAINT \`FK_860f63fd48b93107167e4cd8b41\` FOREIGN KEY (\`delivery_id\`) REFERENCES \`delivery\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`delivery\` ADD CONSTRAINT \`FK_a3b8af1ce2f6e143d416d83080a\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`delivery\` ADD CONSTRAINT \`FK_08f144cd9889759426ab37c358e\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_151b79a83ba240b0cb31b2302d1\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`branches\` ADD CONSTRAINT \`FK_ec93cf21dec41ec5ca617512ef0\` FOREIGN KEY (\`countryId\`) REFERENCES \`countries\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`branches\` ADD CONSTRAINT \`FK_3d3edc7bbc6f133907163ff9cdc\` FOREIGN KEY (\`cityId\`) REFERENCES \`cities\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_has_resource\` ADD CONSTRAINT \`FK_0786b028a20440041f250672598\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_has_resource\` ADD CONSTRAINT \`FK_adb4eb5f4a3119ecd094e849b6f\` FOREIGN KEY (\`resourceId\`) REFERENCES \`resources\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`branch_user_platform_role_resources\` ADD CONSTRAINT \`FK_3ede51a5a949d146e26b63eecf4\` FOREIGN KEY (\`branchId\`) REFERENCES \`branches\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`branch_user_platform_role_resources\` ADD CONSTRAINT \`FK_31e14f979621f93da617ef471eb\` FOREIGN KEY (\`userPlatformRoleId\`) REFERENCES \`user_platform_roles\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`branch_user_platform_role_resources\` ADD CONSTRAINT \`FK_5f460d6c0561c29ff555b547b72\` FOREIGN KEY (\`resourceId\`) REFERENCES \`resources\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_platform_roles\` ADD CONSTRAINT \`FK_6e938f0a49cbab66bddbd1a9f29\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_platform_roles\` ADD CONSTRAINT \`FK_776271ed8c8d191d4801eb6f2a0\` FOREIGN KEY (\`platformId\`) REFERENCES \`platforms\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_platform_roles\` ADD CONSTRAINT \`FK_99f27c650d2ff6bfae0dbfd6186\` FOREIGN KEY (\`roleId\`) REFERENCES \`roles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`colis\` ADD CONSTRAINT \`FK_e289b1e43a171c317c670772e34\` FOREIGN KEY (\`senderId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`colis\` ADD CONSTRAINT \`FK_f145618caef910659c18eee5a17\` FOREIGN KEY (\`receiverId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`colis\` ADD CONSTRAINT \`FK_a9b1f60b903acae377ea9fdd76d\` FOREIGN KEY (\`driverId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_993cd4e93dc84f17341702d059e\` FOREIGN KEY (\`activeCompanyId\`) REFERENCES \`company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_ca511885113fd45b6de7ce6dd43\` FOREIGN KEY (\`defaultAddressId\`) REFERENCES \`address_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` ADD CONSTRAINT \`FK_6c36c7c118fa460ce0dbef078a1\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` ADD CONSTRAINT \`FK_ec55a6c7815580309ec3aa1f808\` FOREIGN KEY (\`companyId\`) REFERENCES \`company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` ADD CONSTRAINT \`FK_695609416765da022418983a827\` FOREIGN KEY (\`roleId\`) REFERENCES \`role_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`assign_permissions\` ADD CONSTRAINT \`FK_ef1d0964292fac8cc56878638e8\` FOREIGN KEY (\`userHasCompanyId\`) REFERENCES \`user_has_company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`assign_permissions\` ADD CONSTRAINT \`FK_ba4be57d802e47d3726bb784af3\` FOREIGN KEY (\`permissionId\`) REFERENCES \`permissions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`assign_permissions\` DROP FOREIGN KEY \`FK_ba4be57d802e47d3726bb784af3\``);
        await queryRunner.query(`ALTER TABLE \`assign_permissions\` DROP FOREIGN KEY \`FK_ef1d0964292fac8cc56878638e8\``);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` DROP FOREIGN KEY \`FK_695609416765da022418983a827\``);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` DROP FOREIGN KEY \`FK_ec55a6c7815580309ec3aa1f808\``);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` DROP FOREIGN KEY \`FK_6c36c7c118fa460ce0dbef078a1\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_ca511885113fd45b6de7ce6dd43\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_993cd4e93dc84f17341702d059e\``);
        await queryRunner.query(`ALTER TABLE \`colis\` DROP FOREIGN KEY \`FK_a9b1f60b903acae377ea9fdd76d\``);
        await queryRunner.query(`ALTER TABLE \`colis\` DROP FOREIGN KEY \`FK_f145618caef910659c18eee5a17\``);
        await queryRunner.query(`ALTER TABLE \`colis\` DROP FOREIGN KEY \`FK_e289b1e43a171c317c670772e34\``);
        await queryRunner.query(`ALTER TABLE \`user_platform_roles\` DROP FOREIGN KEY \`FK_99f27c650d2ff6bfae0dbfd6186\``);
        await queryRunner.query(`ALTER TABLE \`user_platform_roles\` DROP FOREIGN KEY \`FK_776271ed8c8d191d4801eb6f2a0\``);
        await queryRunner.query(`ALTER TABLE \`user_platform_roles\` DROP FOREIGN KEY \`FK_6e938f0a49cbab66bddbd1a9f29\``);
        await queryRunner.query(`ALTER TABLE \`branch_user_platform_role_resources\` DROP FOREIGN KEY \`FK_5f460d6c0561c29ff555b547b72\``);
        await queryRunner.query(`ALTER TABLE \`branch_user_platform_role_resources\` DROP FOREIGN KEY \`FK_31e14f979621f93da617ef471eb\``);
        await queryRunner.query(`ALTER TABLE \`branch_user_platform_role_resources\` DROP FOREIGN KEY \`FK_3ede51a5a949d146e26b63eecf4\``);
        await queryRunner.query(`ALTER TABLE \`user_has_resource\` DROP FOREIGN KEY \`FK_adb4eb5f4a3119ecd094e849b6f\``);
        await queryRunner.query(`ALTER TABLE \`user_has_resource\` DROP FOREIGN KEY \`FK_0786b028a20440041f250672598\``);
        await queryRunner.query(`ALTER TABLE \`branches\` DROP FOREIGN KEY \`FK_3d3edc7bbc6f133907163ff9cdc\``);
        await queryRunner.query(`ALTER TABLE \`branches\` DROP FOREIGN KEY \`FK_ec93cf21dec41ec5ca617512ef0\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_151b79a83ba240b0cb31b2302d1\``);
        await queryRunner.query(`ALTER TABLE \`delivery\` DROP FOREIGN KEY \`FK_08f144cd9889759426ab37c358e\``);
        await queryRunner.query(`ALTER TABLE \`delivery\` DROP FOREIGN KEY \`FK_a3b8af1ce2f6e143d416d83080a\``);
        await queryRunner.query(`ALTER TABLE \`tracking\` DROP FOREIGN KEY \`FK_860f63fd48b93107167e4cd8b41\``);
        await queryRunner.query(`ALTER TABLE \`sub_orders\` DROP FOREIGN KEY \`FK_8960953c62922b12d952670105b\``);
        await queryRunner.query(`ALTER TABLE \`sub_orders\` DROP FOREIGN KEY \`FK_99d5f29c6ea3cfca35f10759984\``);
        await queryRunner.query(`ALTER TABLE \`address_user\` DROP FOREIGN KEY \`FK_2990f79ef381b67c8d5e3474981\``);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` DROP FOREIGN KEY \`FK_3e16264f60cbd62bf1906b79815\``);
        await queryRunner.query(`ALTER TABLE \`company\` DROP FOREIGN KEY \`FK_d37b1b0cc9656c160b5464ac4f3\``);
        await queryRunner.query(`ALTER TABLE \`company\` DROP FOREIGN KEY \`FK_4b47f280258a2e73f5c44497e83\``);
        await queryRunner.query(`ALTER TABLE \`company\` DROP FOREIGN KEY \`FK_9731df468316e5b1a689b906240\``);
        await queryRunner.query(`ALTER TABLE \`measures\` DROP FOREIGN KEY \`FK_10e59b90eb894294b367bddd689\``);
        await queryRunner.query(`ALTER TABLE \`room\` DROP FOREIGN KEY \`FK_a81b8055e21ed129a8c3b153042\``);
        await queryRunner.query(`ALTER TABLE \`booking\` DROP FOREIGN KEY \`FK_336b3f4a235460dc93645fbf222\``);
        await queryRunner.query(`ALTER TABLE \`room_image\` DROP FOREIGN KEY \`FK_8652478a73dd49bbfcf14775e3e\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_f3cd3ac28f81bbb08bd7d119e04\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_1530a6f15d3c79d1b70be98f2be\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_9a5f6868c96e0069e699f33e124\``);
        await queryRunner.query(`ALTER TABLE \`reservations\` DROP FOREIGN KEY \`FK_aa0e1cc2c4f54da32bf8282154c\``);
        await queryRunner.query(`ALTER TABLE \`room_availability\` DROP FOREIGN KEY \`FK_14d1e68b0329da0642313398db2\``);
        await queryRunner.query(`ALTER TABLE \`wishlists\` DROP FOREIGN KEY \`FK_063c6f46d6cbebf35f3a5ec3d4e\``);
        await queryRunner.query(`ALTER TABLE \`wishlists\` DROP FOREIGN KEY \`FK_4f3c30555daa6ab0b70a1db772c\``);
        await queryRunner.query(`ALTER TABLE \`sale_transaction\` DROP FOREIGN KEY \`FK_b517ae8cf8b49878540f36fe038\``);
        await queryRunner.query(`ALTER TABLE \`rental_contracts\` DROP FOREIGN KEY \`FK_b294413af7e26f6dbf73f8ee7e7\``);
        await queryRunner.query(`ALTER TABLE \`category\` DROP FOREIGN KEY \`FK_1117b4fcb3cd4abb4383e1c2743\``);
        await queryRunner.query(`ALTER TABLE \`services\` DROP FOREIGN KEY \`FK_5b16b7b2857ee7d0efab4cf3df1\``);
        await queryRunner.query(`ALTER TABLE \`services\` DROP FOREIGN KEY \`FK_25334fffe4ce341dd1da38acbd9\``);
        await queryRunner.query(`ALTER TABLE \`services\` DROP FOREIGN KEY \`FK_034b52310c2d211bc979c3cc4e8\``);
        await queryRunner.query(`ALTER TABLE \`product_variations\` DROP FOREIGN KEY \`FK_a0def70d267bba28e183f92c7a8\``);
        await queryRunner.query(`ALTER TABLE \`image_product_entity\` DROP FOREIGN KEY \`FK_bcec19dad6b0a68e42913470653\``);
        await queryRunner.query(`ALTER TABLE \`otp_entity\` DROP FOREIGN KEY \`FK_d8d7d1cd42eafbb1d6c61b2ff37\``);
        await queryRunner.query(`DROP INDEX \`IDX_52a3990233b74dd8bc03acae89\` ON \`user_platform_roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_17f1be9ef9af82fee0ab2f6bcc\` ON \`branch_user_platform_role_resources\``);
        await queryRunner.query(`DROP INDEX \`IDX_5629f2896ea05ee200f7a96af4\` ON \`wishlists\``);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`legal\` \`legal\` longtext COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`termsOfUse\` \`termsOfUse\` longtext COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`privacyPolicy\` \`privacyPolicy\` longtext COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`config\` \`config\` longtext COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`seo\` \`seo\` longtext COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`support\` \`support\` longtext COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`address\` \`address\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`booking_phone\` \`booking_phone\` varchar(50) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`rental_phone\` \`rental_phone\` varchar(50) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`car_phone\` \`car_phone\` varchar(50) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`restaurant_phone\` \`restaurant_phone\` varchar(50) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`market_phone\` \`market_phone\` varchar(50) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`service_phone\` \`service_phone\` varchar(50) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`phone\` \`phone\` varchar(50) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`email\` \`email\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`logo\` \`logo\` text COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`slogan\` \`slogan\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`app_settings\` CHANGE \`appName\` \`appName\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`type_companies\` CHANGE \`image\` \`image\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`type_companies\` CHANGE \`description\` \`description\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`assign_permissions\` CHANGE \`permissionId\` \`permissionId\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`assign_permissions\` CHANGE \`userHasCompanyId\` \`userHasCompanyId\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` CHANGE \`roleId\` \`roleId\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` CHANGE \`companyId\` \`companyId\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_has_company\` CHANGE \`userId\` \`userId\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`defaultAddressId\` \`defaultAddressId\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`activeCompanyId\` \`activeCompanyId\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`socketId\` \`socketId\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`twoFASecret\` \`twoFASecret\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`licenseDocumentUrl\` \`licenseDocumentUrl\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`plateNumber\` \`plateNumber\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`vehicleType\` \`vehicleType\` enum COLLATE "utf8mb4_unicode_ci" ('MOTO', 'CAMION', 'VÉLO', 'VOITURE') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`dateOfBirth\` \`dateOfBirth\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`loyaltyPoints\` \`loyaltyPoints\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`preferredLanguage\` \`preferredLanguage\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`address\` \`address\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`provider\` \`provider\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`city\` \`city\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`country\` \`country\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`image\` \`image\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phone\` \`phone\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`email\` \`email\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`colis\` CHANGE \`photos\` \`photos\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`colis\` CHANGE \`driverId\` \`driverId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_platform_roles\` CHANGE \`roleId\` \`roleId\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_platform_roles\` CHANGE \`platformId\` \`platformId\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_platform_roles\` CHANGE \`userId\` \`userId\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_52a3990233b74dd8bc03acae89\` ON \`user_platform_roles\` (\`userId\`, \`platformId\`, \`roleId\`)`);
        await queryRunner.query(`ALTER TABLE \`branch_user_platform_role_resources\` CHANGE \`resourceId\` \`resourceId\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`branch_user_platform_role_resources\` CHANGE \`userPlatformRoleId\` \`userPlatformRoleId\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`branch_user_platform_role_resources\` CHANGE \`branchId\` \`branchId\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_17f1be9ef9af82fee0ab2f6bcc\` ON \`branch_user_platform_role_resources\` (\`branchId\`, \`userPlatformRoleId\`, \`resourceId\`)`);
        await queryRunner.query(`ALTER TABLE \`user_has_resource\` CHANGE \`resourceId\` \`resourceId\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_has_resource\` CHANGE \`userId\` \`userId\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`branches\` CHANGE \`cityId\` \`cityId\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`branches\` CHANGE \`countryId\` \`countryId\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`branches\` CHANGE \`email\` \`email\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`branches\` CHANGE \`phone\` \`phone\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`branches\` CHANGE \`address\` \`address\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`pin\` \`pin\` varchar(6) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`status\` \`status\` enum COLLATE "utf8mb4_unicode_ci" ('PENDING', 'VALIDATED', 'PROCESSING', 'COMPLETED', 'DELIVERED', 'REJECTED') NOT NULL DEFAULT ''PENDING''`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`invoiceNumber\` \`invoiceNumber\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`order_id\` \`order_id\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`user_id\` \`user_id\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`signedAt\` \`signedAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`signatureImageUrl\` \`signatureImageUrl\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`estimatedDeliveryTime\` \`estimatedDeliveryTime\` time NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`deliveredAt\` \`deliveredAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`delivery\` CHANGE \`notes\` \`notes\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tracking\` CHANGE \`delivery_id\` \`delivery_id\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tracking\` CHANGE \`notes\` \`notes\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tracking\` CHANGE \`location\` \`location\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sub_orders\` CHANGE \`companyId\` \`companyId\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sub_orders\` CHANGE \`orderId\` \`orderId\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sub_orders\` CHANGE \`status\` \`status\` enum COLLATE "utf8mb4_unicode_ci" ('PENDING', 'VALIDATED', 'PROCESSING', 'COMPLETED', 'DELIVERED', 'REJECTED') NOT NULL DEFAULT ''PENDING''`);
        await queryRunner.query(`ALTER TABLE \`sub_orders\` CHANGE \`invoiceNumber\` \`invoiceNumber\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`address_user\` CHANGE \`userId\` \`userId\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`seatNumber\` \`seatNumber\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`reservationDate\` \`reservationDate\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`arrivalDate\` \`arrivalDate\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`departureDate\` \`departureDate\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`arrivalLocation\` \`arrivalLocation\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`travel_reservations\` CHANGE \`departureLocation\` \`departureLocation\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`cityId\` \`cityId\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`categoryId\` \`categoryId\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`countryId\` \`countryId\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`localCurrency\` \`localCurrency\` varchar(22) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`longitude\` \`longitude\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`latitude\` \`latitude\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`address\` \`address\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`open_time\` \`open_time\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`distance_km\` \`distance_km\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`delivery_minutes\` \`delivery_minutes\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`website\` \`website\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`email\` \`email\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`logo\` \`logo\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`banner\` \`banner\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`warehouseLocation\` \`warehouseLocation\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`registrationDocumentUrl\` \`registrationDocumentUrl\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`vatNumber\` \`vatNumber\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`companyAddress\` \`companyAddress\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`countries\` CHANGE \`code\` \`code\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`measures\` CHANGE \`company_id\` \`company_id\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`room\` CHANGE \`measureId\` \`measureId\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`room\` CHANGE \`description\` \`description\` text COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`booking\` CHANGE \`userId\` \`userId\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`room_image\` CHANGE \`roomId\` \`roomId\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`room_image\` CHANGE \`altText\` \`altText\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`measureId\` \`measureId\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`brand_id\` \`brand_id\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`category_id\` \`category_id\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`localization\` \`localization\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`image\` \`image\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`ingredients\` \`ingredients\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`dailyRate_price_original\` \`dailyRate_price_original\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`color\` \`color\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`salePrice\` \`salePrice\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`dailyRate\` \`dailyRate\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`year\` \`year\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`model\` \`model\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`registrationNumber\` \`registrationNumber\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`type\` \`type\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`gros\` \`gros\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`detail\` \`detail\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`gros_price_original\` \`gros_price_original\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`detail_price_original\` \`detail_price_original\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`price\` \`price\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`description\` \`description\` text COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`invoiceNumber\` \`invoiceNumber\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`reason\` \`reason\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`specialRequest\` \`specialRequest\` text COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`room_availability\` CHANGE \`productId\` \`productId\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`brands\` CHANGE \`type\` \`type\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`brands\` CHANGE \`image\` \`image\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`wishlists\` CHANGE \`productId\` \`productId\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`wishlists\` CHANGE \`userId\` \`userId\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`wishlists\` CHANGE \`shopType\` \`shopType\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_5629f2896ea05ee200f7a96af4\` ON \`wishlists\` (\`userId\`, \`productId\`)`);
        await queryRunner.query(`ALTER TABLE \`sale_transaction\` CHANGE \`saleNumber\` \`saleNumber\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sale_transaction\` CHANGE \`paymentStatus\` \`paymentStatus\` enum COLLATE "utf8mb4_unicode_ci" ('PENDING', 'PAID', 'VALIDATED', 'PROCESSING', 'COMPLETED', 'DELIVERED', 'REJECTED') NOT NULL DEFAULT ''PENDING''`);
        await queryRunner.query(`ALTER TABLE \`rental_contracts\` CHANGE \`rentalNumber\` \`rentalNumber\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rental_contracts\` CHANGE \`endDate\` \`endDate\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rental_contracts\` CHANGE \`startDate\` \`startDate\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`parent_id\` \`parent_id\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`color\` \`color\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`type\` \`type\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`image\` \`image\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`category\` ADD CONSTRAINT \`FK_1117b4fcb3cd4abb4383e1c2743\` FOREIGN KEY (\`parent_id\`) REFERENCES \`category\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`specification\` DROP COLUMN \`options\``);
        await queryRunner.query(`ALTER TABLE \`specification\` ADD \`options\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`specification\` CHANGE \`unit\` \`unit\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`specification\` CHANGE \`image\` \`image\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_specification_value\` CHANGE \`value\` \`value\` text COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`services\` CHANGE \`categoryId\` \`categoryId\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`services\` CHANGE \`measureId\` \`measureId\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`services\` CHANGE \`companyId\` \`companyId\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`services\` CHANGE \`images\` \`images\` longtext COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`services\` CHANGE \`price\` \`price\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`services\` CHANGE \`description\` \`description\` text COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`services\` ADD CONSTRAINT \`FK_034b52310c2d211bc979c3cc4e8\` FOREIGN KEY (\`categoryId\`) REFERENCES \`category\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`services\` ADD CONSTRAINT \`FK_5b16b7b2857ee7d0efab4cf3df1\` FOREIGN KEY (\`measureId\`) REFERENCES \`measures\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`services\` ADD CONSTRAINT \`FK_25334fffe4ce341dd1da38acbd9\` FOREIGN KEY (\`companyId\`) REFERENCES \`company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`service_has_prestataire\` CHANGE \`tarif\` \`tarif\` decimal(10,0) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`prestataires\` CHANGE \`specialite\` \`specialite\` text COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`prestataires\` CHANGE \`competence\` \`competence\` text COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`prestataires\` CHANGE \`experience\` \`experience\` text COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`prestataires\` CHANGE \`image\` \`image\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`prestataires\` CHANGE \`description\` \`description\` text COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`prestataires\` CHANGE \`phone\` \`phone\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`prestataires\` CHANGE \`email\` \`email\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`attributes\` CHANGE \`description\` \`description\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` CHANGE \`position\` \`position\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` CHANGE \`imageUrl\` \`imageUrl\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` CHANGE \`color\` \`color\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`attribute_values\` CHANGE \`displayName\` \`displayName\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_variations\` CHANGE \`imageId\` \`imageId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_variations\` CHANGE \`barcode\` \`barcode\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_variations\` CHANGE \`height\` \`height\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_variations\` CHANGE \`width\` \`width\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_variations\` CHANGE \`length\` \`length\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_variations\` CHANGE \`weight\` \`weight\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`product_variations\` ADD CONSTRAINT \`FK_a0def70d267bba28e183f92c7a8\` FOREIGN KEY (\`imageId\`) REFERENCES \`image_product_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`image_product_entity\` CHANGE \`productId\` \`productId\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`image_product_entity\` ADD CONSTRAINT \`FK_bcec19dad6b0a68e42913470653\` FOREIGN KEY (\`productId\`) REFERENCES \`products\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`otp_entity\` CHANGE \`userId\` \`userId\` varchar(36) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`otp_entity\` CHANGE \`expiresAt\` \`expiresAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`otp_entity\` ADD CONSTRAINT \`FK_d8d7d1cd42eafbb1d6c61b2ff37\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`permissions\` CHANGE \`description\` \`description\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL DEFAULT 'NULL'`);
    }

}
