export enum IncidentStatus {
    DETECTED = 'DETECTED',
    CLASSIFIED = 'CLASSIFIED',
    ASSIGNED = 'ASSIGNED',
    INVESTIGATING = 'INVESTIGATING',
    FIXED = 'FIXED',
    VALIDATED = 'VALIDATED',
    RESOLVED = 'RESOLVED',
}