export enum ScheduleStatus {
  SCHEDULED = 'SCHEDULED',
  DEPARTED = 'DEPARTED',
  EN_ROUTE = 'EN_ROUTE',
  ARRIVED = 'ARRIVED',
  CANCELLED = 'CANCELLED',
  DELAYED = 'DELAYED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
}
