export enum CompanyType {
  RESTAURANT = 'RESTAURANT',
  CAR = 'CAR',
  GROCERY = 'GROCERY',
  SHOP = 'SHOP',
  SERVICE = 'SERVICE',
  HOTEL = 'HOTEL',
  SHIPPING = 'SHIPPING',
  AGENCE = 'AGENCE',
}
