export enum PaymentStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  VALIDATED = 'VALIDATED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  DELIVERED = 'DELIVERED',
  REJECTED = 'REJECTED ',
}
