export enum ShipmentStatus {
  PENDING = 'PENDING',
  PICKUP_ASSIGNED = 'PICKUP_ASSIGNED',
  PICKUP_IN_PROGRESS = 'PICKUP_IN_PROGRESS',
  PICKUP_COMPLETED = 'PICKUP_COMPLETED',
  AT_ORIGIN_AGENCY = 'AT_ORIGIN_AGENCY',
  AWAITING_SHIPPING = 'AWAITING_SHIPPING',
  SHIPPING_IN_PROGRESS = 'SHIPPING_IN_PROGRESS',
  ARRIVED_DESTINATION = 'ARRIVED_DESTINATION',
  READY_FOR_DELIVERY = 'READY_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
}
