export enum PrestataireType {
  
  TECHNICIEN = 'TECHNICIEN',
  ELECTRICIEN = 'ELECTRICIEN',
  PLOMBIER = 'PLOMBIER',
  MECANICIEN = 'MECANICIEN',
  INFORMATICIEN = 'INFORMATICIEN',
  INSTALLATEUR = 'INSTALLATEUR',
  CHAUFFAGISTE = 'CHAUFFAGISTE',
  AGENT_ENTRETIEN = 'AGENT_ENTRETIEN',

  CHAUFFEUR = 'CHAUFFEUR',
  LIVREUR = 'LIVREUR',
  CONDUCTEUR = 'CONDUCTEUR',
  AGENT_LOGISTIQUE = 'AGENT_LOGISTIQUE',

  MEDECIN = 'MEDECIN',
  INFIRMIER = 'INFIRMIER',
  PHARMACIEN = 'PHARMACIEN',
  KINESITHERAPEUTE = 'KINESITHERAPEUTE',
  PSYCHOLOGUE = 'PSYCHOLOGUE',
  AGENT_SANTE = 'AGENT_SANTE',

  CONSULTANT = 'CONSULTANT',
  FORMATEUR = 'FORMATEUR',
  COACH = 'COACH',
  EXPERT = 'EXPERT',
  TUTEUR = 'TUTEUR',

  MACON = 'MACON',
  PEINTRE = 'PEINTRE',
  CARRELEUR = 'CARRELEUR',
  MENUISIER = 'MENUISIER',
  ARCHITECTE = 'ARCHITECTE',
  INGENIEUR_CIVIL = 'INGENIEUR_CIVIL',

  DESIGNER = 'DESIGNER',
  DEVELOPPEUR = 'DEVELOPPEUR',
  PHOTOGRAPHE = 'PHOTOGRAPHE',
  VIDEASTE = 'VIDEASTE',
  COMMUNITY_MANAGER = 'COMMUNITY_MANAGER',

  CUISINIER = 'CUISINIER',
  SERVEUR = 'SERVEUR',
  FEMME_MENAGE = 'FEMME_MENAGE',
  RECEPTIONNISTE = 'RECEPTIONNISTE',

  COIFFEUR = 'COIFFEUR',
  ESTHETICIEN = 'ESTHETICIEN',
  MAQUILLEUR = 'MAQUILLEUR',
  BARBIER = 'BARBIER',
  MASSEUR = 'MASSEUR',

  AGRICULTEUR = 'AGRICULTEUR',
  PECHEUR = 'PECHEUR',
  JARDINIER = 'JARDINIER',
  AGENT_ENVIRONNEMENT = 'AGENT_ENVIRONNEMENT',

  COMPTABLE = 'COMPTABLE',
  SECRETAIRE = 'SECRETAIRE',
  AGENT_ADMINISTRATIF = 'AGENT_ADMINISTRATIF',
  SUPERVISEUR = 'SUPERVISEUR',

  ARTISTE = 'ARTISTE',
  ANIMATEUR = 'ANIMATEUR',
  AUTRE = 'AUTRE',
}
