export enum PrestataireRole {

  RESPONSABLE = 'RESPONSABLE',
  CHEF_EQUIPE = 'CHEF_EQUIPE',
  TECHNICIEN = 'TECHNICIEN',
  OPERATEUR = 'OPERATEUR',
  CONSULTANT = 'CONSULTANT',
  FORMATEUR = 'FORMATEUR',

  ASSISTANT = 'ASSISTANT',
  SECRETAIRE = 'SECRETAIRE',
  COMPTABLE = 'COMPTABLE',
  AGENT_ADMINISTRATIF = 'AGENT_ADMINISTRATIF',

  LIVREUR = 'LIVREUR',
  CHAUFFEUR = 'CHAUFFEUR',
  AGENT_ENTRETIEN = 'AGENT_ENTRETIEN',
  AGENT_LOGISTIQUE = 'AGENT_LOGISTIQUE',

  AUTRE = 'AUTRE',
}
