export enum NotificationType {
  SHOP = 'shop',
  DEALER = 'dealer',
  FOOD = 'food',
  SERVICE = 'service',
  GROCERY = 'grocery',
  ECOMMERCE = 'ecommerce',
  PRODUCT = 'product',
  COMPANY = 'company',
  NEW_RIDE = 'new_ride',
  RIDE_ACCEPTED = 'ride_accepted',
  RIDE_CANCELLED = 'ride_cancelled',
  LOGISTIC = 'LOGISTIC',
  ORDER_CREATED = 'order_created',
  ORDER_UPDATED = 'order_updated',
  SHIPMENT_CREATED = 'shipment_created',
  RESERVATION_CREATED = 'reservation_created',

  WISHLIST = 'wishlist',
  WISHLIST_REMINDER = 'wishlist_reminder',
  PROMOTION = 'promotion',
  NEWSLETTER = 'newsletter',
  TRIP_REMINDER = 'trip_reminder',
  TRIP_UPDATED = 'trip_updated',
  TRIP_CANCELLED = 'trip_cancelled',
  RESERVATION_UPDATED = 'reservation_updated',
  RESERVATION_CONFIRMED = 'reservation_confirmed',
  RESERVATION_CANCELLED = 'reservation_cancelled',
  TICKET_SCANNED = 'ticket_scanned',
  PAYMENT_SUCCESS = 'payment_success',
  PAYMENT_FAILED = 'payment_failed',
  STOCK_ALERT = 'stock_alert',
  LOW_STOCK = 'low_stock',
  REVIEW_REQUEST = 'review_request',
  DELIVERY_UPDATED = 'delivery_updated',
  DELIVERY_DELIVERED = 'delivery_delivered',
  PASSWORD_RESET = 'password_reset',
  LOGIN_ALERT = 'login_alert',
  ACCOUNT_SUSPENDED = 'account_suspended',

  SHIPMENT_REMINDER = 'shipment_reminder',
  SHIPMENT_TRACKING = 'shipment_tracking',
  SHIPMENT_PROMOTION = 'shipment_promotion',
  HOME_DELIVERY = 'home_delivery',
  LTA_NEW_ROUTES = 'lta_new_routes',
  LTA_PENDING = 'lta_pending',

  SERVICE_NEW = 'service_new',
  SERVICE_POPULAR = 'service_popular',

  HOTEL_REMINDER = 'hotel_reminder',
  HOTEL_CHECKOUT = 'hotel_checkout',

  PRESTATAIRE_NEW = 'prestataire_new',
  PRESTATAIRE_REMINDER = 'prestataire_reminder',
}
