export enum ProductStatus {
  PENDING = 'PENDING',
  REJECTED = 'REJECTED',
  PUBLISHED = 'PUBLISHED',
  AVAILABLE = 'AVAILABLE',
  RENTED = 'RENTED',
  SOLD = 'SOLD',
  MAINTENANCE = 'MAINTENANCE',
}
